/**
 * Type definitions and static constants for the Finance page.
 * No business logic — pure TypeScript declarations.
 */

export type TxType = "مصروف" | "إيراد";
// "suppressed" = auto entry deleted by user; persisted in DB with amount=0 so it
// won't be regenerated by the auto-sync. Filtered from all UI views.
export type SourceType = "auto" | "manual" | "suppressed";
export type Category =
  | "حجز ملعب"
  | "رواتب"
  | "اشتراكات"
  | "أدوات"
  | "تسويق"
  | "صيانة"
  | "مواصلات"
  | "أخرى";

export type FinanceTx = {
  id: string;
  month: string;
  dateISO: string;
  type: TxType;
  branchId: string;
  category: Category;
  amount: number;
  note?: string;
  source: SourceType;
  autoKey?: string;
  overriddenAutoKey?: string;
  createdAtISO: string;
  updatedAtISO?: string;
};

export type BranchLite = { id: string; name: string; rent_type: string; monthly_rent: number; days: string[] };

export type StaffLite = {
  id: string;
  name: string;
  role: string;
  jobTitle?: string;
  monthlySalary: number;
  branchIds: string[];
  isActive: boolean;
};

export type Payment = {
  id: string;
  dateISO: string;
  branchId: string | null;
  playerId: string;
  amount: number;
  kind: "new" | "renew" | "legacy";
};

export type SortKey = "date_desc" | "date_asc" | "amount_desc" | "amount_asc";

export type SubItem = {
  id: string;
  date?: string;
  label: string;
  amount: number; // negative = saving/deduction
};

export type GroupedTxView = {
  tx: FinanceTx;
  subItems: SubItem[];
  grossAmount: number; // tx.amount + abs(sum of negative sub-items) — for expanded header
};

export type PrintMode = "main_only" | "with_sub" | "revenues" | "expenses" | "all";

// ── Static UI constants ────────────────────────────────────────────────────────

export const CATEGORY_STYLES: Record<string, string> = {
  "اشتراكات":  "bg-[#00ff9c]/10 text-[#00ff9c] border-[#00ff9c]/20",
  "حجز ملعب":  "bg-cyan-400/10 text-cyan-300 border-cyan-400/20",
  "رواتب":     "bg-amber-400/10 text-amber-300 border-amber-400/20",
  "أدوات":     "bg-sky-400/10 text-sky-300 border-sky-400/20",
  "تسويق":     "bg-purple-400/10 text-purple-300 border-purple-400/20",
  "صيانة":     "bg-orange-400/10 text-orange-300 border-orange-400/20",
  "مواصلات":   "bg-indigo-400/10 text-indigo-300 border-indigo-400/20",
  "أخرى":      "bg-white/8 text-white/55 border-white/10",
};

export const CATEGORIES: Category[] = [
  "اشتراكات", "حجز ملعب", "رواتب", "أدوات", "تسويق", "صيانة", "مواصلات", "أخرى",
];
